GARNAME = cssh
GARVERSION = beta-0.03
CATEGORIES = apps

DESCRIPTION = This is a test of an smf-enabled package.
define BLURB
  The program just sleeps. It's about writing SMF manifests and stuff.
endef

ARCHALL = 1
MASTER_SITES = $(SF_MIRRORS)
DISTFILES  = $(GARNAME)_$(GARVERSION).tar.bz2

REQUIRED_PKGS = CSWperl

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS =
TEST_SCRIPTS =
INSTALL_SCRIPTS =

include gar/category.mk
